name: SQL Server Integration Tests
on: push
jobs:
  container-job:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
      max-parallel: 5
    steps:
      - uses: actions/checkout@v2
      - name: Generate random password
        shell: bash -l {0}
        run: |
          echo "export SA_PASSWORD=SaPQvrZ$RANDOM" > pass.sh
      - name: Install sqlserver
        shell: bash -l {0}
        run: |
          sudo curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
          sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/18.04/mssql-server-2019.list)"
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-server
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc
      - name: List files
        run: |
            ls -l /opt/
            ls -l /opt/mssql
            ls -l /opt/mssql/bin
            ls -l /opt/mssql-tools
            ls -l /opt/mssql-tools/bin
      - name: Clone test datasets
        run: |
          git clone https://github.com/opendp/dp-test-datasets.git
      - name: Start SQL Server
        run: |
            source pass.sh
            sudo MSSQL_SA_PASSWORD=$SA_PASSWORD /opt/mssql/bin/mssql-conf -n setup accept-eula
      - name: Install PUMS
        shell: bash -l {0}
        run: |
          source pass.sh
          export DATA=`pwd`/dp-test-datasets/data/
          cd tests/sdk/engines/sqlserver/PUMS
          source install.sh
      # - name: Set up miniconda
      #   uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     miniconda-version: "latest"
      #     auto-update-conda: true
      #     auto-activate-base: true
      #     python-version: ${{ matrix.python-version }}
      # - name: Upgrade pip
      #   shell: bash -l {0}
      #   run: |
      #     conda install pip
      #     conda update pip
