SELECT ID, COUNT(ID) AS C FROM BAZ GROUP BY BAZ;
SELECT 1 + COUNT(ID) AS C FROM BAZ;
SELECT 1 FROM BAR;
SELECT COUNT(ID) AS N FROM B GROUP BY ID;
SELECT ID, COUNT(ID) AS N FROM B GROUP BY ID;
SELECT COUNT(ID) FROM BAZ GROUP BY ID;
SELECT SUM(Sales) FROM (SELECT Sales, ID FROM XX GROUP BY ID);