
name: tutorial
channels:
  - defaults
dependencies:
  - python=3.7
  - numpy>=1.14.3
  - pandas==0.25.3
  - scikit-learn=0.19.1
  - pip
  - pip:
    - mlflow
    - pyemd
    - imblearn
    - scipy
    - diffprivlib
    - torch
    - opacus
    - ctgan
    - git+https://github.com/opendp/smartnoise-sdk#subdirectory=sdk
