# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class LocalCSVDetails(Model):
    """LocalCSVDetails.

    :param local_path: Path to the csv on diskThe type of the dataset
    :type local_path: str
    """

    _attribute_map = {
        'local_path': {'key': 'local_path', 'type': 'str'},
    }

    def __init__(self, local_path=None):
        super(LocalCSVDetails, self).__init__()
        self.local_path = local_path
