# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ProjectRunDetails(Model):
    """ProjectRunDetails.

    :param project_uri: Git url of the project
    :type project_uri: str
    :param params: Input parameters of the project
    :type params: str
    """

    _attribute_map = {
        'project_uri': {'key': 'project_uri', 'type': 'str'},
        'params': {'key': 'params', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(ProjectRunDetails, self).__init__(**kwargs)
        self.project_uri = kwargs.get('project_uri', None)
        self.params = kwargs.get('params', None)
