# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DataverseDetails(Model):
    """DataverseDetails.

    :param local_metadata_path:
    :type local_metadata_path: str
    :param token: Contains the datasets secret, with name and value
    :type token: str
    :param host: Host of dataset, if dataverse
    :type host: str
    :param schema: Schema of dataset, well formed json
    :type schema: str
    """

    _attribute_map = {
        'local_metadata_path': {'key': 'local_metadata_path', 'type': 'str'},
        'token': {'key': 'token', 'type': 'str'},
        'host': {'key': 'host', 'type': 'str'},
        'schema': {'key': 'schema', 'type': 'str'},
    }

    def __init__(self, local_metadata_path=None, token=None, host=None, schema=None):
        super(DataverseDetails, self).__init__()
        self.local_metadata_path = local_metadata_path
        self.token = token
        self.host = host
        self.schema = schema
