SELECT [FOO.BAR] FROM Baz;
SELECT [Employee Name] FROM [The Table.];
SELECT SQL FROM SomeTable;
SELECT Bar FROM UNION;
SELECT Foo. FROM BAR;
SELECT FOO FROM .BAZ;
SELECT FOO FR OM .BAZ;
SELECT *.* FROM BAZ;
SELECT FF FROM BAZ.*;