name: SQL code linter

on:
  pull_request:
    paths:
      - ".github/actions/setup-python-uv/**"
      - ".github/workflows/lint_sql.yml"
      - "sql/snsql/**"
      - "tox.ini"
      - "!sql/tests/setup/postgres/**"
      - "!sql/tests/setup/sqlserver/**"
      - "!sql/tests/setup/mysql/**"
      - "!sql/tests/setup/bigquery/**"
  workflow_dispatch:

permissions:
  contents: read

env:
  DEFAULT_PYTHON_VERSION: "3.12"

jobs:
  lint-sql:
    name: SQL code linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up repo bootstrap
        uses: ./.github/actions/setup-python-uv
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          package-specs: |
            flake8

      - name: Lint with flake8
        run: |
          flake8 sql/snsql/sql/dpsu.py -v
          flake8 sql/snsql/reader/ -v
