name: SQL on Spark

on:
  pull_request:
    paths:
      - 'sql/tests/**'
      - 'sql/snsql/**'
      - 'sql/pyproject.toml'
  workflow_dispatch:
  
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
      max-parallel: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        auto-activate-base: true
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      shell: bash -l {0}
      run: |
        conda install pip
        conda update pip
    - name: Install Java
      shell: bash -l {0}
      run: |
        sudo apt-get update
        sudo apt-get -yq upgrade
        sudo apt-get -yq install openjdk-11-jre-headless
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        cd sql
        pip install --no-cache-dir -r tests/requirements.txt
        pip install --no-cache-dir pyspark
    - name: Install smartnoise-sql
      shell: bash -l {0}
      run: |
        cd sql
        pip install --no-cache-dir .
        export TEST_SPARK=1
        export SKIP_PANDAS=1
        python tests/check_databases.py
    - name: Test SDK
      shell: bash -l {0}
      run: |
        cd sql
        export TEST_SPARK=1
        export SKIP_PANDAS=1
        pytest tests
