name: Synthesizers Unit Tests

on:
  pull_request:
    paths:
      - ".github/actions/setup-python-uv/**"
      - ".github/workflows/synth.yml"
      - "sql/snsql/**"
      - "sql/pyproject.toml"
      - "synth/tests/**"
      - "synth/snsynth/**"
      - "synth/pyproject.toml"
  workflow_dispatch:

permissions:
  contents: read

env:
  DEFAULT_PYTHON_VERSION: "3.12"

jobs:
  build-linux:
    name: Synthesizers Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up repo bootstrap
        uses: ./.github/actions/setup-python-uv
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          editable-projects: |
            sql
            synth
          requirements-files: |
            synth/tests/requirements.txt

      - name: Test SDK
        run: |
          cd synth
          python -m pytest tests
