name: Synthesizers Unit Tests

on:
  pull_request:
    paths:
      - 'synth/tests/**'
      - 'synth/snsynth/**'
      - 'synth/pyproject.toml'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
      max-parallel: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        auto-activate-base: true
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      shell: bash -l {0}
      run: |
        conda install pip
        conda update pip
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        cd synth
        pip install --no-cache-dir -r tests/requirements.txt
    - name: Install smartnoise-synth
      shell: bash -l {0}
      run: |
        cd synth
        pip install --no-cache-dir .
    - name: Test SDK
      shell: bash -l {0}
      run: |
        cd synth
        python -m pytest tests
