name: SQL on Pandas on Windows
on:
  pull_request:
    paths:
      - 'sql/tests/**'
      - 'sql/snsql/**'
      - 'sql/pyproject.toml'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: pip install smartnoise-sql
        shell: cmd
        run: |
          cd sql
          pip install --no-cache-dir -r tests\requirements.txt
          pip install --no-cache-dir .
      - name: Unit tests
        shell: cmd
        run: |
          cd sql
          pytest tests
